---
title: "BCN demo"
author: "daniel.lundin@lnu.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
format:
  html:
    code-fold: true
    toc: true
    embed-resources: true
bibliography:
  - bibliography.bib
  - grateful-refs.bib
---

```{r setup}
#| label: setup
#| echo: false
#| cache: false

knitr::opts_chunk$set(echo = TRUE, fig.path='figures/', cache = TRUE, fig.width = 10)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries}
#| label: libraries
#| message: false
#| cache: false
#| include: false

library(readr)
library(tibble)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)
library(kfigr)
library(knitr)
library(DT)
library(grateful)
library(patchwork)
```

```{r constants}
#| label: constants
```

```{r read-counts}
#| label: read-counts
counts <- read_tsv(
  'data/p19_06/ASV_table.tsv', 
  col_types = cols(.default = col_integer(), ASV_ID = col_character())
) %>%
  pivot_longer(2:ncol(.), names_to = 'sample', values_to = 'count') %>%
  filter(count > 0) %>%
  rename_with(str_to_lower) %>%
  group_by(sample) %>%
  mutate(relab = count/sum(count)) %>%
  ungroup()
```

```{r read-taxonomy}
#| label: read-taxonomy
taxonomy <- read_tsv(
  'data/p19_06/p19_06.ASV_tax_species.sbdi-gtdb_R09-RS220-1.tsv',
  show_col_types = FALSE
) %>%
  rename_with(str_to_lower)
```

# Version history

# Summary

# Introduction

# Materials and Methods

## Amplicon annotation

* nf-core/ampliseq [@ampliseq]

## R and packages

This analysis was run with `r R.version$version.string`. Versions of packages used can be found in @tbl-cite-packages.

```{r tbl-cite-packages}
#| label: tbl-cite-packages
#| cache: false
#| tbl-cap: Versions of R and packages used in this analysis.

cite_packages(output = "table", pkgs = "Session", out.dir = getwd()) %>%
  kable()
```

# Results

## Community composition

```{r fig-phyla}
#| label: fig-phyla
counts %>%
  inner_join(taxonomy, by = join_by(asv_id)) %>%
  group_by(phylum, sample) %>%
  summarise(relab = sum(relab), .groups = 'drop') %>%
  ggplot(aes(x = sample, y = relab, fill = phylum)) +
  geom_col()
```


# Discussion

# References

```{r}
# vim: sw=2
```
